### ISSUE TITLE
[TASK] - Main Menu

### ISSUE THREAD

**Issue by MerseyHubGroup-BM** [MerseyHubGroup/Website#4]
**URL**
All Pages

**Summary of task**
Update of DEV Links

**Task to-do list**

- [x] Update Mersey Hub Group
- [x] Update Mersey Animal Hub
- [x] Update Mersey Hosting Hub
- [x] Update Mersey Community Hub

**Additional context**

**Comment by MerseyHubGroup-BM** [comment]
Completed.
